# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14e0148b946eb5504b363536d99dd3076a5a06d029d9c99fcaeea3f0c6be3f2536e2ebc63b2bc95b39c97dfe4aa8cb5dca10f48e19a077e330fe5e77c6113b9b
  facebook_app_id: 1672832339653386
  facebook_app_secret: 2ae0ebcc325f72f98dd015d71192deb1
  vk_id: 5232658
  vk_secret: vE0SFXAUDEdmgUjZmhGI
test:
  secret_key_base: fcd4eb984cc28c8b046bc0c754b1d4fbd95f610258c25570f972bbf74e0eaa9c77324e9c0d3975e2edfe1f4cac4c4a920ce706ab5b417e8a25b28cabc0fe5e29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_app_id: <%= ENV["FACEBOOK_APP_SECRET"] %>
  vk_id: <%= ENV["VK_ID"] %>
  vk_id: <%= ENV["VK_SECRET"] %>